# Generated by Django 5.2.2 on 2025-06-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_content',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
