# Generated by Django 5.2.2 on 2025-06-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_rule_rule_content'),
    ]

    operations = [
    ]
