# Generated by Django 5.2.2 on 2025-07-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='encoding',
            field=models.BinaryField(null=True),
        ),
    ]
