# Generated by Django 5.2.4 on 2025-07-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentinfo_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_type',
            field=models.IntegerField(choices=[(1, 'Điểm 15 phút'), (2, 'Điểm 1 tiết'), (3, 'Điểm thi cuối kỳ')]),
        ),
    ]
