# Generated by Django 5.2.4 on 2025-08-12 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_score_score_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conduct', models.CharField(choices=[('T', 'Tốt'), ('K', 'Khá'), ('TB', 'Trung bình'), ('Y', 'Yếu'), ('CX', 'Chưa xét')], default='CX', max_length=2)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_records', to='students.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_records', to='students.studentinfo')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
